import { profile, stats, skillGroups, focusAreas, projects, experience, education } from "@/lib/data";
import Image from "next/image";
import ProjectFilter from "@/components/ProjectFilter";

const Arrow = () => <span aria-hidden="true">↗</span>;

export default function Home() {
  return <div className="min-h-screen overflow-hidden"><Nav /><main><Hero /><About /><FocusAreas /><Skills /><Projects /><Experience /><Education /><Contact /></main><Footer /></div>;
}

function Nav() {
  const links = [["About", "#about"], ["Expertise", "#focus"], ["Projects", "#projects"], ["Experience", "#experience"]];
  return <header className="sticky top-0 z-30 border-b border-white/8 bg-bg/75 backdrop-blur-xl"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4 sm:px-8"><a href="#top" className="group flex items-center gap-2 font-mono text-sm font-medium tracking-tight"><span className="signal-dot" />{profile.name.split(" ")[0].toLowerCase()}<span className="text-copper">.dev</span></a><nav className="hidden items-center gap-6 lg:flex">{links.map(([label, href]) => <a key={href} href={href} className="nav-link">{label}</a>)}</nav><a href={profile.resumeUrl} className="button button-small button-ghost">Resume <Arrow /></a></div></header>;
}

function Hero() {
  return <section id="top" className="hero-section relative isolate"><div className="hero-grid" aria-hidden /><div className="orb orb-one" aria-hidden /><div className="orb orb-two" aria-hidden /><div className="relative mx-auto grid max-w-6xl items-center gap-14 px-5 pb-20 pt-20 sm:px-8 sm:pb-28 sm:pt-28 lg:grid-cols-[1.25fr_.75fr]"><div className="reveal"><div className="eyebrow"><span className="live-dot" /> available for new opportunities</div><h1 className="hero-title">Building <em>intelligent</em><br />systems at the<br /><span>edge of possible.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-muted">{profile.tagline}</p><p className="mt-4 font-mono text-xs tracking-wide text-muted/80">{profile.name} <span className="mx-2 text-copper">//</span> {profile.location}</p><div className="mt-9 flex flex-wrap gap-3"><a href="#projects" className="button button-primary">Explore selected work <Arrow /></a><a href="#contact" className="button button-ghost">Let&apos;s work together</a></div></div><div className="hero-visual reveal-delay"><div className="photo-card"><div className="photo-noise" aria-hidden /><Image src={profile.photo} alt={profile.name} width={420} height={420} priority className="h-full w-full object-cover grayscale transition duration-700 hover:scale-105 hover:grayscale-0" /><div className="photo-label">SYSTEMS / AI / ROBOTICS</div><span className="photo-corner top-0 left-0" /><span className="photo-corner top-0 right-0 rotate-90" /><span className="photo-corner bottom-0 left-0 -rotate-90" /><span className="photo-corner bottom-0 right-0 rotate-180" /></div><div className="stats-card">{stats.map((s, i) => <div key={s.label} className={`stat ${i ? "border-t border-white/10" : ""}`}><span>{s.label}</span><strong>{s.value}</strong></div>)}</div></div></div><a className="scroll-cue" href="#about"><span /> Scroll to discover</a></section>;
}

function About() { return <section id="about" className="section-shell"><SectionHeading number="01" title="The person behind the systems" /><div className="grid gap-10 lg:grid-cols-[.62fr_1.38fr]"><p className="font-mono text-xs uppercase tracking-[.18em] text-teal">A computer engineer who likes bringing software into the physical world.</p><p className="max-w-3xl text-xl leading-relaxed text-muted sm:text-2xl">I got into computer vision and embedded systems wanting to build things that could actually sense and react to the physical world, not just run in a browser tab. I now work across perception, control, and product-minded web development — building models and systems that make real-time decisions on limited hardware.</p></div></section>; }
function FocusAreas() { return <section id="focus" className="section-shell"><SectionHeading number="02" title="What I bring to the table" /><div className="service-grid">{focusAreas.map((area, index) => <article key={area.title} className="service-card"><span className="service-number">0{index + 1}</span><h3>{area.title}</h3><p>{area.description}</p><div className="mt-auto flex flex-wrap gap-2 pt-7">{area.tools.map((t) => <span key={t} className="tech-pill">{t}</span>)}</div></article>)}</div></section>; }
function Skills() { return <section id="skills" className="section-shell"><SectionHeading number="03" title="Technical toolkit" /><div className="skill-grid">{skillGroups.map((group, i) => <article key={group.category} className="skill-card"><span className="font-mono text-xs text-copper">{String(i + 1).padStart(2, "0")}</span><h3>{group.category}</h3><ul>{group.items.map((item) => <li key={item}><span>✦</span>{item}</li>)}</ul></article>)}</div></section>; }
function Projects() { return <section id="projects" className="section-shell projects-section"><SectionHeading number="04" title="Selected experiments & builds" /><ProjectFilter projects={projects} /></section>; }
function Experience() { return <section id="experience" className="section-shell"><SectionHeading number="05" title="Experience" /><div className="timeline">{experience.map((e) => <article key={e.title} className="timeline-item"><p className="font-mono text-xs text-copper">{e.period}</p><div><p className="text-xl font-semibold">{e.title}</p><p className="mt-1 font-mono text-sm text-teal">{e.org}</p><p className="mt-4 max-w-2xl text-muted">{e.description}</p></div></article>)}</div></section>; }
function Education() { return <section id="education" className="section-shell"><SectionHeading number="06" title="Education" /><div className="timeline">{education.map((e) => <article key={e.degree} className="timeline-item"><p className="font-mono text-xs text-copper">{e.period}</p><div><p className="text-xl font-semibold">{e.degree}</p><p className="mt-1 font-mono text-sm text-teal">{e.school}</p>{e.description && <p className="mt-4 max-w-2xl text-muted">{e.description}</p>}</div></article>)}</div></section>; }
function Contact() { return <section id="contact" className="px-5 pb-24 pt-10 sm:px-8"><div className="contact-panel mx-auto max-w-6xl"><p className="eyebrow"><span className="live-dot" /> start a conversation</p><h2>Have a challenging<br />problem to <em>solve?</em></h2><p>Open to roles in computer vision, embedded ML, robotics, and thoughtful web products.</p><div className="mt-8 flex flex-wrap gap-3"><a href={`mailto:${profile.email}`} className="button button-primary">Email me <Arrow /></a><a href={profile.github} className="button button-ghost">GitHub <Arrow /></a><a href={profile.linkedin} className="button button-ghost">LinkedIn <Arrow /></a></div></div></section>; }
function Footer() { return <footer className="border-t border-white/8 px-5 py-7 sm:px-8"><div className="mx-auto flex max-w-6xl flex-wrap justify-between gap-3 font-mono text-xs text-muted"><span>© {new Date().getFullYear()} {profile.name}</span><span>DESIGNED TO SHIP REAL THINGS</span></div></footer>; }
function SectionHeading({ number, title }: { number: string; title: string }) { return <div className="section-heading"><span>{number}</span><h2>{title}</h2><i /></div>; }
